

name: .NET Core Desktop

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test-app: 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Restore dependencies
      run: dotnet restore "Projet_Calculatrice_CICD/Projet_Calculatrice_CICD.sln"
    
    - name: Build
      run: dotnet build "Projet_Calculatrice_CICD/Projet_Calculatrice_CICD.sln" --configuration Debug --no-restore

    - name: Vibin
      run: ls "/home/runner/work/Calculatrice_Projet_Test_CICD/Calculatrice_Projet_Test_CICD/Projet_Test_Calculatrice/bin/Debug/net8.0/"
        
    - name: Run tests
      run: dotnet test "Projet_Calculatrice_CICD/Projet_Calculatrice_CICD.sln" --no-build --verbosity normal
